import { Geist, Geist_Mono , outfit } from "next/font/google";
import "./globals.css";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";

import Header from "./_components/Header";
import ReduxProvider from "./redux/ReduxProvider";
import Footer from "./_components/Footer";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="">
      
      <body
        className={`${geistSans.variable} ${geistMono.variable}  antialiased`}
      >
        <ReduxProvider>
        <div>
          <Header/>
          <div className="">
          {children}
          </div>
        <Footer/>
        </div>
        </ReduxProvider>
       
      </body>
    </html>
  );
}
